server:
  port: 40000
spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/epecuen
    username: root
    password: 123456
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      listener:
        type: single
    #      acks: all
    #      retries: 3
    #      properties:
    #        enable.idempotence: true
    #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: user-service-group
      auto-offset-reset: earliest
#      enable-auto-commit: true
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.trusted.packages: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
