server:
  port: 40000
spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:mysql://localhost:3306/epecuen
    username: root
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"